# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MarsRoversPhotos' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MarsRoversPhotos
  pod 'Alamofire'
  pod 'AlamofireImage'

  target 'MarsRoversPhotosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarsRoversPhotosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
